spring:
  datasource:
    url: jdbc:sqlserver://springserver.database.windows.net:1433;database=spring;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: Abdur
    password: Abd@man2003
  jpa:
    show-sql : true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191

